### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by sckott** [AustralianAntarcticDivision/ropenblog#3]
nice draft.

> For Antarctic and Southern Ocean studies, it is very common to deal with satellite, model, or other environmental data.

Curious why this is?

For the `raadtools` section: curious where the data comes from? What agencies?

**Comment by raymondben** [comment]
Thanks @sckott.
- environmental: just because Antarctic/SO science tends to be dominated by physical environmental considerations. Added note:
> The physical environment is important to a large cross-section of Antarctic science ...

- agencies: lots. Bowerbird/blueant are intended to be agency-agnostic. Note added:
> [blueant] encompasses data such as sea ice, bathymetry and land topography, oceanography, and atmospheric reanalysis and weather predictions, from providers such as NASA, NOAA, Copernicus, NSIDC, and Ifremer.
